import bannerImg from './assets/images/meat_cuts_banner_1790897447370.jpg';
import picanhaImg from './assets/images/prime_picanha_offer_1790897457625.jpg';
import chickenImg from './assets/images/chicken_cuts_offer_1790897466955.jpg';
import ribsImg from './assets/images/ribs_costela_offer_1790898518746.jpg';
import linguicaImg from './assets/images/linguica_toscana_offer_1790898530707.jpg';
import { Category, MeatItem, StoreSettings } from './types.ts';

export { bannerImg, picanhaImg, chickenImg, ribsImg, linguicaImg };

export interface CutPhotoOption {
  id: string;
  name: string;
  url: string;
  isCustom?: boolean;
}

export const PRESET_CUT_PHOTOS: CutPhotoOption[] = [
  { id: 'p_chicken', name: 'Coxa & Sobrecoxa de Frango', url: chickenImg },
  { id: 'p_picanha', name: 'Picanha Nobre Premium', url: picanhaImg },
  { id: 'p_ribs', name: 'Costela Gaúcha Bovina', url: ribsImg },
  { id: 'p_linguica', name: 'Linguiça Toscana Artesanal', url: linguicaImg },
  { id: 'p_banner', name: 'Cortes Nobres Variados', url: bannerImg },
];

export const CATEGORIES: Category[] = [
  { id: 'todos', label: 'Todos os Cortes', shortLabel: 'Todos' },
  { id: 'bovinos', label: 'Carnes Bovinas', shortLabel: 'Bovinos' },
  { id: 'aves', label: 'Frango & Aves', shortLabel: 'Aves' },
  { id: 'suinos', label: 'Carnes Suínas', shortLabel: 'Suínos' },
  { id: 'embutidos', label: 'Linguiças & Embutidos', shortLabel: 'Embutidos' },
  { id: 'especiais', label: 'Churrasco & Especiais', shortLabel: 'Churrasco' },
];

export const DEFAULT_SETTINGS: StoreSettings = {
  storeName: 'CASA DE CARNES & AÇOUGUE BOI NOBRE',
  storeSubtitle: 'Cortes Selecionados • Carnes Frescas Diariamente • Tradição & Qualidade',
  phone: '(11) 3456-7890',
  whatsapp: '(11) 98765-4321',
  tickerMessage: '🥩 CARNES NOBRES E FRESCAS TODOS OS DIAS! • ACEITAMOS PIX, CARTÕES DE CRÉDITO, DÉBITO E VALE ALIMENTAÇÃO (ALELO, SODEXO, VR) • FAÇA SEU PEDIDO PELO WHATSAPP: (11) 98765-4321 • QUALIDADE GARANTIDA!',
  theme: 'wood_dark',
  columns: 2,
  showClock: true,
  showBannerImage: true,
  bannerImageUrl: bannerImg,
  autoRotateOffers: true,
  rotationIntervalSeconds: 8,
  soundAlertOnPriceUpdate: true,
  tvZoom: 100,
  currencySymbol: 'R$',
  featuredPhotoSize: 'large',
  featuredPhotoFit: 'cover',
  adminPin: '1310',
  requirePinForAdmin: true,
  column1Title: 'AVES, SUÍNOS & ESPECIAIS',
  column2Title: 'CORTES BOVINOS NOBRES',
  badgeInitials: 'BN',
  badgeTitle: 'BOI NOBRE',
  badgeSubtitle: 'CASA DE CARNES',
  bannerBadgeText: 'Qualidade & Procedência 100% Inspecionada',
  nightModeEnabled: false,
  nightModeAuto: false,
  nightModeStartHour: 19,
  nightModeEndHour: 7,
  nightModeDimLevel: 65,
  maintenanceModeEnabled: false,
  maintenanceTitle: 'SISTEMA EM ATUALIZAÇÃO',
  maintenanceMessage: 'Estamos atualizando nossa tabela de cortes e preços para você. Retornaremos em instantes!',
  maintenanceEstimatedReturn: 'Retorno em poucos minutos',
};

export const DEFAULT_MEAT_ITEMS: MeatItem[] = [
  // Aves e Suinos (Left column in photo)
  {
    id: 'm1',
    name: 'COXA DE FRANGO',
    category: 'aves',
    price: 19.90,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 1,
  },
  {
    id: 'm2',
    name: 'SOBRECOXA DE FRANGO',
    category: 'aves',
    price: 20.90,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 2,
  },
  {
    id: 'm3',
    name: 'FILÉ DE PEITO DE FRANGO',
    category: 'aves',
    price: 28.50,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 3,
  },
  {
    id: 'm4',
    name: 'COXA E SOBRECOXA',
    category: 'aves',
    price: 5.79,
    originalPrice: 17.90,
    unit: 'kg',
    isOffer: true,
    isFeaturedDaily: true,
    featuredSubtitle: 'SUPER OFERTA DA SEMANA • CORTE FRESCO',
    featuredImage: chickenImg,
    available: true,
    order: 4,
  },
  {
    id: 'm5',
    name: 'PICADINHO DE FRANGO',
    category: 'aves',
    price: 23.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 5,
  },
  {
    id: 'm6',
    name: 'COSTELINHA DE PORCO',
    category: 'suinos',
    price: 32.90,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 6,
  },
  {
    id: 'm7',
    name: 'PERNIL SUÍNO (PEÇA)',
    category: 'suinos',
    price: 29.90,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 7,
  },
  {
    id: 'm8',
    name: 'SORUNA',
    category: 'bovinos',
    price: 26.50,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 8,
  },
  {
    id: 'm9',
    name: 'LINGUIÇA TOSCANA',
    category: 'embutidos',
    price: 26.50,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 9,
  },
  {
    id: 'm10',
    name: 'LINGUIÇA DE PERNIL ARTESANAL',
    category: 'embutidos',
    price: 34.90,
    unit: 'kg',
    isOffer: true,
    isFeaturedDaily: false,
    available: true,
    order: 10,
  },

  // Bovinos (Right column in photo)
  {
    id: 'm11',
    name: 'PICANHA PREMIUM',
    category: 'bovinos',
    price: 79.90,
    originalPrice: 89.90,
    unit: 'kg',
    isOffer: true,
    isFeaturedDaily: true,
    featuredSubtitle: 'CORTE NOBRE MATURADO • CAPA DE GORDURA PADRÃO',
    featuredImage: picanhaImg,
    available: true,
    order: 11,
  },
  {
    id: 'm12',
    name: 'ALCATRA COM MAMINHA',
    category: 'bovinos',
    price: 68.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 12,
  },
  {
    id: 'm13',
    name: 'CONTRA FILÉ',
    category: 'bovinos',
    price: 65.90,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 13,
  },
  {
    id: 'm14',
    name: 'FILÉ MIGNON',
    category: 'bovinos',
    price: 98.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 14,
  },
  {
    id: 'm15',
    name: 'FRALDINHA',
    category: 'bovinos',
    price: 62.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 15,
  },
  {
    id: 'm16',
    name: 'CHÃ DE DENTRO',
    category: 'bovinos',
    price: 58.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 16,
  },
  {
    id: 'm17',
    name: 'ACÉM MOÍDO',
    category: 'bovinos',
    price: 45.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 17,
  },
  {
    id: 'm18',
    name: 'CARNE SOL',
    category: 'bovinos',
    price: 52.00,
    unit: 'kg',
    isOffer: false,
    isFeaturedDaily: false,
    available: true,
    order: 18,
  },
  {
    id: 'm19',
    name: 'COSTELA GAÚCHA',
    category: 'bovinos',
    price: 39.90,
    unit: 'kg',
    isOffer: true,
    isFeaturedDaily: false,
    available: true,
    order: 19,
  },
  {
    id: 'm20',
    name: 'KIT CHURRASCO',
    category: 'especiais',
    price: 120.00,
    originalPrice: 145.00,
    unit: 'kit',
    isOffer: true,
    isFeaturedDaily: false,
    featuredSubtitle: '1kg Picanha + 1kg Linguiça + 1kg Frango + Pão de Alho',
    available: true,
    order: 20,
  },
];
